name: Action thru Push
on:
    push:
        branches: '**'

jobs:
    build:
        name: Build simple project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
            - name: Install dependencies
              run: npm install
            - name: Test project
              run: npm test
